ERROR_FLAGS_OFFSET = 80
ERROR_FLAGS_MASK = 0x7

SCA_ADDR_OFFSET = 72
SCA_ADDR_MASK = 0xFF

CONTROL_OFFSET = 64
CONTROL_MASK = 0xFF

TRANSACTION_ID_OFFSET = 56
TRANSACTION_ID_MASK = 0xFF

CHANNEL_ADDR_OFFSET = 48
CHANNEL_ADDR_MASK = 0xFF

NBYTES_PAYLOAD_OFFSET = 40
NBYTES_PAYLOAD_MASK = 0xFF

ERROR_OFFSET = 32
ERROR_MASK = 0xFF

PAYLOAD_OFFSET = 0
PAYLOAD_MASK = 0xFFFFFFFF
