BROADCAST_ADDR_OFFSET = 88
BROADCAST_ADDR_MASK = 0xFFFFFFFFFF

REPLY_ADDR_OFFSET = 68
REPLY_ADDR_MASK = 0x3F

COMMAND_ID_OFFSET = 64
COMMAND_ID_MASK = 0x7

SCA_ADDR_OFFSET = 56
SCA_ADDR_MASK = 0xFF

TRANSACTION_ID_OFFSET = 48
TRANSACTION_ID_MASK = 0xFF

CHANNEL_ADDR_OFFSET = 40
CHANNEL_ADDR_MASK = 0xFF

COMMAND_OFFSET = 32
COMMAND_MASK = 0xFF

PAYLOAD_OFFSET = 0
PAYLOAD_MASK = 0xFFFFFFFF
